# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    sciAdmin:
                        password: e=mc2
                        roles: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout:
                path: /logout
                target: http://127.0.0.1:8000/

    access_control:
        - {path: ^/admin, roles: ROLE_ADMIN}

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
