app_admin_publication_index:
    path:     /
    defaults: { _controller: "AppBundle:Publication:index" }
    methods:  GET

app_admin_publication_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Publication:show" }
    methods:  GET

app_admin_publication_new:
    path:     /new
    defaults: { _controller: "AppBundle:Publication:new" }
    methods:  [GET, POST]

app_admin_publication_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Publication:edit" }
    methods:  [GET, POST]

app_admin_publication_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Publication:delete" }
    methods:  DELETE
