app_admin_science_index:
    path:     /
    defaults: { _controller: "AppBundle:Science:index" }
    methods:  GET

app_admin_science_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Science:show" }
    methods:  GET

app_admin_science_new:
    path:     /new
    defaults: { _controller: "AppBundle:Science:new" }
    methods:  [GET, POST]

app_admin_science_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Science:edit" }
    methods:  [GET, POST]

app_admin_science_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Science:delete" }
    methods:  DELETE
